CREATE TABLE [dbo].[SportModel]
(
	[Id] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [description] VARCHAR(50) NULL, 
    [type] INT NULL, 
    [start_date_local] VARCHAR(50) NULL, 
    [start_date_localSpecified] BIT NULL, 
    [scheduled_start_time_utc] VARCHAR(50) NULL, 
    [scheduled_start_time_utcSpecified] BIT NULL, 
    [end_time] VARCHAR(50) NULL, 
    [end_timeSpecified] BIT NULL, 
    [status] INT NULL, 
    [statusSpecified] BIT NULL, 
    [names] VARCHAR(50) NULL, 
    [current_state] VARCHAR(50) NULL, 
    [attendance] INT NULL, 
    [attendanceSpecified] BIT NULL, 
    [sport_id] VARCHAR(50) NULL, 
    [venue_id] VARCHAR(50) NULL, 
    [start_venue_id] INT NULL, 
    [finish_venue_id] INT NULL, 
    [phase_id] VARCHAR(50) NULL, 
    [event_attributes] VARCHAR(50) NULL, 
    [sports_discipline_id] VARCHAR(50) NULL, 
    [sports_gender_id] VARCHAR(50) NULL, 
    [sibling_order] INT NULL, 
    [sibling_orderSpecified] BIT NULL, 
    [schedule_status] INT NULL, 
    [schedule_statusSpecified] BIT NULL, 
    [result_status] INT NULL, 
    [result_statusSpecified] BIT NULL, 
    [event_type_detail] INT NULL, 
    [event_type_detailSpecified] bit null, 
    [direct_parent_sports_event_id] VARCHAR(50) NULL, 
    [home_participant_id] VARCHAR(50) NULL, 
    [away_participant_id] VARCHAR(50) NULL, 
    [participant_type] INT NULL, 
    [participant_typeSpecified] BIT NULL, 
    [translation_reference_id] VARCHAR(50) NULL, 
    [sports] VARCHAR(50) NULL, 
    [sports_organizations] VARCHAR(50) NULL, 
    [venues] VARCHAR(50) NULL, 
    [child_sports_events] VARCHAR(50) NULL, 
    [xids] VARCHAR(50) NULL,

    
)
